name: StatsAPI-HolographicDisplays
version: 1.0.2
depend:
  - StatsAPI
softdepend:
  - HolographicDisplays
website: https://www.spigotmc.org/resources/statsapi-holographicdisplays-addon.74963/
main: de.devsnx.statsapi.addon.StatsAPIAddon