name: StatsAPI-HolographicDisplays
version: 1.0.1
depend:
  - HolographicDisplays
  - StatsAPI
website: https://www.spigotmc.org/resources/statsapi-holographicdisplays-addon.74963/
main: de.snx.statsapi.addon.StatsAPIAddon